/*
 Java_Program_1_Test_Cases:
    Lines of Code : 102
    Number of Test Cases : 5
    Test Cases:
        1)Input:
            4
            2
            caa
            cbb
            3
            cba
            cba
            cbb
            4
            ccab
            cbac
            bca
            acbcc
            4
            acb
            caf
            c
            cbafc
        Output:
            YES
            NO
            YES
            NO
            
            
        2)Input:
            1
            1000
            s
            k
            r
            m
            a
            b
            n
            k
            h
            n
            l
            f
            i
            p
            a
            t
            d
            o
            x
            x
            h
            t
            w
            p
            u
            l
            h
            l
            s
            v
            e
            z
            j
            x
            z
            o
            k
            y
            w
            m
            i
            e
            m
            z
            x
            v
            r
            d
            b
            g
            n
            p
            o
            s
            h
            c
            y
            j
            y
            i
            y
            t
            f
            x
            m
            i
            z
            d
            z
            d
            d
            i
            n
            z
            h
            g
            k
            k
            q
            k
            d
            f
            l
            c
            z
            j
            y
            e
            y
            s
            l
            a
            b
            l
            c
            n
            f
            h
            v
            v
            f
            i
            l
            t
            b
            r
            i
            a
            a
            u
            v
            w
            b
            j
            h
            p
            u
            k
            y
            u
            h
            s
            o
            d
            b
            f
            t
            r
            e
            v
            h
            e
            m
            g
            k
            l
            h
            p
            n
            e
            b
            n
            g
            h
            r
            p
            z
            a
            z
            e
            j
            a
            e
            d
            f
            i
            k
            c
            z
            r
            f
            w
            t
            u
            c
            m
            p
            i...
        Output:
            NO


        3)Input:
            10
            5
            ted
            t
            yt
            rr
            bt
            30
            dirg
            otngt
            ti
            hric
            wjcxv
            nhb
            xe
            abs
            xspj
            s
            puhud
            k
            gg
            bajl
            bhf
            qjvtlu
            iuqvx
            lqnub
            ocyr
            fpuc
            fqai
            vkx
            eahas
            zg
            pietg
            moj
            cj
            udbleqcb
            mnylb
            c
            8
            xkc
            hebz
            wp
            urm
            kxbutp
            tkxy
            xnpyb
            kwdaz
            63
            h
            whx
            zn
            ya
            d
            l
            ud
            ko
            f
            m
            b
            sr
            f
            h
            w
            m
            upc
            jr
            iol
            dtvtw
            nk
            t
            ic
            m
            gdcs
            hjvm
            ry
            y
            xcy
            tuyj
            h
            ix
            k
            l
            o
            g
            ou
            jqnn
            o
            tz
            hci
            n
            y
            tjw
            nbd
            kq
            nx
            jmhh
            kq
            s
            il
            px
            o
            w
            pvz
            n
            yi
            g
            vd
            x
            ihmrz
            ctv
            nw
            1
            y
            ...
        Output:
            NO
            NO
            NO
            NO
            YES
            NO
            YES
            YES
            YES
            YES

        
        4)Input:
            7
            10
            qql
            blqqqbqb
            klkbq
            qqqlbbk
            bkq
            bklkqb
            qbq
            lqqqlkq
            qkkk
            qlll
            95
            w
            f
            b
            yd
            r
            z
            h
            f
            fn
            fo
            k
            v
            u
            z
            h
            v
            r
            c
            g
            ds
            e
            z
            v
            er
            c
            zc
            na
            k
            d
            d
            a
            c
            s
            x
            d
            xax
            a
            n
            f
            e
            gj
            w
            t
            eo
            n
            p
            n
            k
            u
            s
            utd
            vl
            dy
            h
            c
            yc
            r
            wf
            j
            u
            i
            cy
            t
            i
            d
            j
            damje
            y
            zg
            c
            m
            j
            l
            s
            ly
            fz
            g
            s
            p
            c
            g
            z
            s
            e
            e
            inj
            c
            i
            b
            ij
            g
            n
            x
            v
            m
            30
            vivs
            v
            svs
            svisvvv
            sv
            vsvi
            vvvvii
            vsisv
            vvsivs
            vvv
            sisv
            si
            iiivi
            vvs
            viii
            vv
            v
            sisisv
            svis
            vvv...
        Output:
            YES
            NO
            YES
            YES
            YES
            NO
            YES


        5)Input:
            4
            2
            caa
            cbb
            3
            cba
            cba
            cbb
            4
            ccab
            cbac
            bca
            acbcc
            4
            acb
            caf
            c
            cbafc
        Output:
            YES
            NO
            YES
            NO


        5)Input:
            1
            228
            uwibc
            lk
            yiznws
            aycl
            itxf
            igl
            jx
            rle
            boxg
            p
            bs
            hrbzsv
            ycdx
            ulkc
            le
            vv
            hf
            am
            engxsl
            jnrpeos
            klge
            aku
            uo
            tdf
            og
            agbsu
            fm
            geli
            gqf
            mq
            xs
            uv
            avywlh
            zxt
            h
            oh
            ixrq
            o
            b
            rx
            v
            oaxk
            qp
            tehspf
            ujdpyo
            f
            eejf
            eet
            cqqh
            ed
            moulouq
            f
            ahh
            e
            uyd
            hbs
            d
            uf
            f
            drczac
            q
            fb
            b
            kepe
            bzdrd
            iddc
            kwqz
            so
            ieiqkb
            kdne
            gfm
            s
            dgiuy
            tzztmb
            nvir
            gkd
            w
            t
            gakq
            mwc
            jox
            jwbh
            zhqkzd
            usjmf
            igjp
            sy
            my
            wr
            ia
            muwu
            dl
            axjv
            vkblx
            ki
            kzu
            aa
            yler
            usv...
        Output:
            NO
        
 */